### ISSUE TITLE
Doesn't work with Rails 4.2, RailsAdmin 0.7.0

### ISSUE THREAD

**Issue by firec0der** [scarfacedeb/rails_admin_globalize_field#20]
Here are my output:
```
/Users/firecoder/.rvm/gems/ruby-2.2.3@gud-rails-admin/gems/rails_admin-0.7.0/lib/rails_admin/config/fields/types/belongs_to_association.rb:7:in `<module:Types>': uninitialized constant RailsAdmin::Config::Fields::Association (NameError)
	from /Users/firecoder/.rvm/gems/ruby-2.2.3@gud-rails-admin/gems/rails_admin-0.7.0/lib/rails_admin/config/fields/types/belongs_to_association.rb:6:in `<module:Fields>'
	from /Users/firecoder/.rvm/gems/ruby-2.2.3@gud-rails-admin/gems/rails_admin-0.7.0/lib/rails_admin/config/fields/types/belongs_to_association.rb:5:in `<module:Config>'
	from /Users/firecoder/.rvm/gems/ruby-2.2.3@gud-rails-admin/gems/rails_admin-0.7.0/lib/rails_admin/config/fields/types/belongs_to_association.rb:4:in `<module:RailsAdmin>'
	from /Users/firecoder/.rvm/gems/ruby-2.2.3@gud-rails-admin/gems/rails_admin-0.7.0/lib/rails_admin/config/fields/types/belongs_to_association.rb:3:in `<top (required)>'
	from /Users/firecoder/.rvm/gems/ruby-2.2.3@gud-rails-admin/gems/rails_admin-0.7.0/lib/rails_admin/config/fields/types/all.rb:2:in `<top (required)>'
	from /Users/firecoder/.rvm/gems/ruby-2.2.3@gud-rails-admin/gems/rails_admin-0.7.0/lib/rails_admin/config/fields/types.rb:23:in `<module:Types>'
	from /Users/firecoder/.rvm/gems/ruby-2.2.3@gud-rails-admin/gems/rails_admin-0.7.0/lib/rails_admin/config/fields/types.rb:8:in `<module:Fields>'
	from /Users/firecoder/.rvm/gems/ruby-2.2.3@gud-rails-admin/gems/rails_admin-0.7.0/lib/rails_admin/config/fields/types.rb:7:in `<module:Config>'
	from /Users/firecoder/.rvm/gems/ruby-2.2.3@gud-rails-admin/gems/rails_admin-0.7.0/lib/rails_admin/config/fields/types.rb:6:in `<module:RailsAdmin>'
	from /Users/firecoder/.rvm/gems/ruby-2.2.3@gud-rails-admin/gems/rails_admin-0.7.0/lib/rails_admin/config/fields/types.rb:5:in `<top (required)>'
	from /Users/firecoder/.rvm/gems/ruby-2.2.3@gud-rails-admin/gems/rails_admin-0.7.0/lib/rails_admin/config/fields.rb:78:in `<top (required)>'
	from /Users/firecoder/.rvm/gems/ruby-2.2.3@gud-rails-admin/gems/rails_admin-0.7.0/lib/rails_admin/config/model.rb:7:in `<top (required)>'
	from /Users/firecoder/.rvm/gems/ruby-2.2.3@gud-rails-admin/gems/rails_admin-0.7.0/lib/rails_admin/config/lazy_model.rb:1:in `<top (required)>'
	from /Users/firecoder/.rvm/gems/ruby-2.2.3@gud-rails-admin/gems/rails_admin-0.7.0/lib/rails_admin/config.rb:1:in `<top (required)>'
	from /Users/firecoder/.rvm/gems/ruby-2.2.3@gud-rails-admin/gems/rails_admin-0.7.0/lib/rails_admin/config/fields/association.rb:1:in `<top (required)>'
	from /Users/firecoder/.rvm/gems/ruby-2.2.3@gud-rails-admin/gems/rails_admin_globalize_field-0.3.1/lib/rails_admin_globalize_field.rb:2:in `<top (required)>'
	from /Users/firecoder/.rvm/gems/ruby-2.2.3@gud-rails-admin/gems/bundler-1.10.6/lib/bundler/runtime.rb:76:in `require'
	from /Users/firecoder/.rvm/gems/ruby-2.2.3@gud-rails-admin/gems/bundler-1.10.6/lib/bundler/runtime.rb:76:in `block (2 levels) in require'
	from /Users/firecoder/.rvm/gems/ruby-2.2.3@gud-rails-admin/gems/bundler-1.10.6/lib/bundler/runtime.rb:72:in `each'
	from /Users/firecoder/.rvm/gems/ruby-2.2.3@gud-rails-admin/gems/bundler-1.10.6/lib/bundler/runtime.rb:72:in `block in require'
	from /Users/firecoder/.rvm/gems/ruby-2.2.3@gud-rails-admin/gems/bundler-1.10.6/lib/bundler/runtime.rb:61:in `each'
	from /Users/firecoder/.rvm/gems/ruby-2.2.3@gud-rails-admin/gems/bundler-1.10.6/lib/bundler/runtime.rb:61:in `require'
	from /Users/firecoder/.rvm/gems/ruby-2.2.3@gud-rails-admin/gems/bundler-1.10.6/lib/bundler.rb:134:in `require'
	from /Volumes/hdd/Dropbox/Dropbox/workspace/RubymineProjects/gud-rails-admin/config/application.rb:7:in `<top (required)>'
	from /Users/firecoder/.rvm/gems/ruby-2.2.3@gud-rails-admin/gems/railties-4.2.4/lib/rails/commands/commands_tasks.rb:78:in `require'
	from /Users/firecoder/.rvm/gems/ruby-2.2.3@gud-rails-admin/gems/railties-4.2.4/lib/rails/commands/commands_tasks.rb:78:in `block in server'
	from /Users/firecoder/.rvm/gems/ruby-2.2.3@gud-rails-admin/gems/railties-4.2.4/lib/rails/commands/commands_tasks.rb:75:in `tap'
	from /Users/firecoder/.rvm/gems/ruby-2.2.3@gud-rails-admin/gems/railties-4.2.4/lib/rails/commands/commands_tasks.rb:75:in `server'
	from /Users/firecoder/.rvm/gems/ruby-2.2.3@gud-rails-admin/gems/railties-4.2.4/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
	from /Users/firecoder/.rvm/gems/ruby-2.2.3@gud-rails-admin/gems/railties-4.2.4/lib/rails/commands.rb:17:in `<top (required)>'
	from bin/rails:4:in `require'
	from bin/rails:4:in `<main>'
```

**Comment by firec0der** [comment]
Oh, it works! I just had problems with other gems. Close this issue.
